version: "3.3"

services:

  postgres:
    image: "postgres:${POSTGRES_VERSION}"
    ports:
      - "5432:5432"
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres:/var/lib/postgresql/data/
    restart: always

  app:
    image: 'docker-spring-boot-api-postgres:latest'
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    container_name: app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_PASSWORD}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  postgres: